services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: build-secret-key
    command: >
      sh -c "python core/manage.py migrate &&
             python core/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:///db.sqlite3
      SECRET_KEY: runtime-secret-key
    stdin_open: true
    tty: true
